### ISSUE TITLE
Can't require interop

### ISSUE THREAD

**Issue by mje113** [ReactiveX/RxJRuby#14]
I think this issue might be due to this repo not being up to date with core RxJava, however when I run:

```
require 'rx/lang/jruby/interop'
```

It errors out with:

```
NameError: cannot load Java class rx.util.functions.Action
         for_name at org/jruby/javasupport/JavaClass.java:1286
  get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
    const_missing at file:/Users/mike/.rvm/rubies/jruby-1.7.19/lib/jruby.jar!/jruby/java/java_package_module_template.rb:4
          Interop at file:/Users/mike/.m2/repository/com/netflix/rxjava/rxjava-jruby/0.20.7/rxjava-jruby-0.20.7.jar!/rx/lang/jruby/interop.rb:19
            Jruby at file:/Users/mike/.m2/repository/com/netflix/rxjava/rxjava-jruby/0.20.7/rxjava-jruby-0.20.7.jar!/rx/lang/jruby/interop.rb:18
             Lang at file:/Users/mike/.m2/repository/com/netflix/rxjava/rxjava-jruby/0.20.7/rxjava-jruby-0.20.7.jar!/rx/lang/jruby/interop.rb:17
               Rx at file:/Users/mike/.m2/repository/com/netflix/rxjava/rxjava-jruby/0.20.7/rxjava-jruby-0.20.7.jar!/rx/lang/jruby/interop.rb:16
           (root) at file:/Users/mike/.m2/repository/com/netflix/rxjava/rxjava-jruby/0.20.7/rxjava-jruby-0.20.7.jar!/rx/lang/jruby/interop.rb:15
          require at org/jruby/RubyKernel.java:1071
           (root) at /Users/mike/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
          require at /Users/mike/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
```

**Comment by mje113** [comment]
Ah... I just realized this is fixed in the 0.x branch but the latest release on Maven doesn't include the fix. Would it be possible to get a new release?

**Comment by MartinNowak** [comment]
Could this still get a new relelase please? @benjchristensen

**Comment by akarnokd** [comment]
We are sorry but this project has been abandoned more than 2 years ago (and is not properly setup for release anyway).
